name: code_forge
description: "A sophisticated code editor package with AI completion, LSP support, syntax highlighting, and advanced editing capabilities."
version: 1.1.0
publish_to: none

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  jinja_app_widgets_catalog:
    git:
      url: git@git.jinja.app:jinja.app/jinja_app_widgets_catalog.git
      ref: dev
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_html: ^3.0.0
  meta: ^1.17.0
  re_highlight:
    path: packages/re-highlight
    # git:
    #   url: https://github.com/AvoMandjian/code_forge.git
    #   ref: DP_V3
    #   path: packages/re-highlight
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  google_fonts: ^6.3.3
  flutter_lints: ^6.0.0
  intl: 0.20.2
  flutter_quill:
    git:
      url: https://github.com/AvoMandjian/flutter-quill.git
      ref: DP
  flutter_quill_extensions:
    git:
      url: https://github.com/AvoMandjian/flutter-quill.git
      path: flutter_quill_extensions
      ref: DP

flutter:
  fonts:
    - family: Method
      fonts:
        - asset: assets/icons/method.ttf
    - family: Variable
      fonts:
        - asset: assets/icons/variable.ttf
    - family: Class
      fonts:
        - asset: assets/icons/class.ttf
    - family: Enum
      fonts:
        - asset: assets/icons/enum.ttf
    - family: KeyWord
      fonts:
        - asset: assets/icons/keyword.ttf
    - family: Reference
      fonts:
        - asset: assets/icons/reference.ttf
    - family: Constant
      fonts:
        - asset: assets/icons/constant.ttf
    - family: Struct
      fonts:
        - asset: assets/icons/struct.ttf
    - family: Event
      fonts:
        - asset: assets/icons/event.ttf
    - family: Operator
      fonts:
        - asset: assets/icons/operator.ttf
    - family: Parameter
      fonts:
        - asset: assets/icons/parameter.ttf
    - family: Snippet
      fonts:
        - asset: assets/icons/snippet.ttf
    - family: Interface
      fonts:
        - asset: assets/icons/interface.ttf
    - family: Field
      fonts:
        - asset: assets/icons/field.ttf
